services:
  obsidian:
    image: alterzz/obsidian-sync-share-server:latest
    container_name: obsidian
    volumes: 
      - ./user_store:/app/user_store
    environment:
      TZ: Europe/Moscow
      JAVA_OPTS: -Xmx512m
    ports:
      - 8000:8080
    restart: unless-stopped
