version: "3.9"
services:
  obsidian:
    image: ghcr.io/sytone/obsidian-remote:latest
    container_name: obsidian
    hostname: obsidian-remote
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
    # ports:
    #   - 4501:8080
    #   - 27123:27123
    #   - 27124:27124
    volumes:
      - /mnt/backup/documents/notes:/vaults:rw
      - ./config_obsidian:/config:rw
    environment:
      PUID: 1026
      PGID: 100
      TZ: Europe/Moscow
      DOCKER_MODS: linuxserver/mods:universal-git
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: volokzhanin